Use half <= 2.3.0
This is required in order to avoid the below issue in our target.

```
error: register class `vreg` requires the `neon` target feature
  --> /home/changho/.cargo/registry/src/index.crates.io-6f17d22bba15001f/half-2.3.1/src/bi
   |
16 |         out(vreg) result,
   |         ^^^^^^^^^^^^^^^^

error: register class `vreg` requires the `neon` target feature
  --> /home/changho/.cargo/registry/src/index.crates.io-6f17d22bba15001f/half-2.3.1/src/bi
   |
17 |         in(vreg) i,
   |         ^^^^^^^^^^
...
```