Comment out deny(clippy::cargo)
This commit is required to avoid the below issue in islet's CI.

```
$ ./scripts/clippy.sh

    Checking ciborium-io v0.2.2 (/root/islet/third-party/ciborium/ciborium-io)
error: package `armv9a` is missing `package.description` metadata
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/in
note: the lint level is defined here
  --> third-party/ciborium/ciborium-io/src/lib.rs:20:9
   |
20 | #![deny(clippy::cargo)]
   |         ^^^^^^^^^^^^^
   = note: `#[deny(clippy::cargo_common_metadata)]` implied by `#[deny(clippy::cargo)]`
...
```